version: "3.8"
services:
  app:
    container_name: node-app
    build:
      context: .
      dockerfile: Dockerfile  # ✅ Use relative path
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo-db:27017/busBookingDB

    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules  # ✅ Prevents node_modules conflict

  mongo:
    container_name: mongo-db
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
